title: Pradeep Loganathan's Blog
description: 'My technical notes and thoughts on software engineering, programming, and life.'
author: Pradeep Loganathan
Copyright: "my copyright"
comments: true
enableSocialMetaTags: true
paginate: 10
images:
  - Pradeep-Loganathan.jpeg
DateFormat: 'January 2, 2006'
timeFormat: 'h:mm a'
dateTimeFormat: 'MMMM Do, YYYY h:mm a'
language: en
editPost:
  URL: "https://github.com/PradeepLoganathan/pradeepl-blog/tree/master/content"
  Text: "Edit this post on github" # edit text
  appendFilePath: true # to append file path to Edit link