baseURL: https://pradeepl.com
languageCode: en-us
title: "Pradeep Loganathan"
paginate: 5
copyright: "&copy; 2023 Pradeep Loganathan.<br> This work is licensed under <br> a Creative Commons Attribution-ShareAlike 4.0 <br> International License."

defaultContentLanguage: en
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
enableGitInfo: true

googleAnalytics: G-LB9Q9F622G

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    noClasses: false
    style: monokai

minify:
  minifyOutput: true
  minifyCSS: true
  minifyJS: true
  minifyHTML: true
  minifyURLs: true
  disableXML: true

outputFormats:
  aacfeed:
    MediaType: "application/rss+xml"
    BaseName: "index"
    path: "/feed/aac"
    IsHTML: false
    IsPlainText: true
    noUgly: true
    Rel: "alternate"
  mp3feed:
    MediaType: "application/rss+xml"
    BaseName: "index"
    path: "/feed/mp3"
    IsHTML: false
    IsPlainText: true
    noUgly: true
    Rel: "alternate"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
        - aacfeed
        - mp3feed
     
menu:
  main:
  - name: About
    params:
    rel: external
    pre: <i class="fa fa-heart"></i>
    url: https://www.linkedin.com/in/pradeeploganathan/
    weight: 50
  - name: Videos
    pageref: /screencasts
    weight: 40
  - name: Podcast
    pageref: /episodes
    weight: 30
  - name: Blog
    pageref: /blog
    weight: 20
  - name: Search
    pageref: /search
    weight: 10

params:
  env: production
  title: "Pradeep Loganathan"
  description: 'My technical notes and thoughts on software engineering, programming, and life.'
  keywords: [Pradeep Loganathan, kubernetes, Devops, GitOps, ArgoCD, FluxCD]
  author: "Pradeep Loganathan"
  email: "pradeep.loganathan@sefd.com"
  comments: true
  images:
    - Pradeep-Loganathan.jpeg
  DateFormat: 'January 2, 2006'
  timeFormat: 'h:mm a'
  dateTimeFormat: 'MMMM Do, YYYY h:mm a'
  language: en-us
  languageCode: en-us

  mainSections: ['posts', "episodes"]

  podcast:
    description: Software engineering podcast - description
    tagline:  Software engineering podcast - tagline
    download_url: https://cdn.pradeepl.com/episodes/
    cdn_url: https://cdn.pradeepl.com/
    itunes_url: https://podcasts.apple.com/us/podcast/cloud-native-engineering/id1620074933
    itunes_id:
    google_podcasts_url: 

  editPost:
    URL: "https://github.com/PradeepLoganathan/pradeepl-blog/tree/master/content"
    Text: "Edit this post on github" # edit text
    appendFilePath: true # to append file path to Edit link

  social:
    twitter: pradeepl    

  header:
    title: 'Pradeep Loganathan'
    imageUrl: 'Pradeep-Loganathan.jpeg'
    subtitle: 'cc'

  label:
    text: "Pradeep Loganathan"
    icon: AllSeeingEye.jpg
    iconHeight: 34
    iconWidth: 245
    smallIcon: AllSeeingEye.jpg
    smallIconHeight: 65
    smallIconWidth: 65

  ShowShareButtons: true
  ShowWordCount: true
  ShowReadingTime: true
  ShowAuthor: true
  ShowBreadCrumbs: true
  ShowTags: true
  ShowCategories: true
  ShowDate: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  hideFooter: true
  ShowRssButtonInSectionTermList: true
  Author: "Pradeep Loganathan"

  taxonomies:
    category: categories
    tag: tags
    series: series
    course: course
    episode: episodes

  homeInfoParams:
      Title: "Hi there \U0001F44B"
      Content: Welcome to my blog.

      subscribeInfo:
        Text: If you liked this post, check out my other [Featured Posts](/categories/featured) or learn more [About Me](/about).  

  socialIcons: # optional
    - name: "twitter"
      url: "https://twitter.com/pradeepl"
    - name: "facebook"
      url: "https://facebook.com/pradeepl"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/pradeeploganathan/"
    - name: "github"
      url: "https://github.com/pradeeploganathan"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/4613054/pradeepl"
    - name: rss
      url: /index.xml

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
    
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


  profileMode:
    enabled: true
    title: "Notes from my journey designing and building software systems" # optional default will be site title
    subtitle: "Software engineering notes"
    imageUrl: "Pradeep-Loganathan.jpeg" # optional
    imageTitle: "Pradeep Loganathan" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: feed
        url: "/index.xml"
      - name: tags
        url: "/tags/"
  
  giscus:
    repo : "PradeepLoganathan/pradeepl-blog"
    repoID : "R_kgDOGrc4sA"
    category : "BlogPosts"
    categoryID : "DIC_kwDOGrc4sM4CRM5A"
    mapping : "og:title"
    reactionsEnabled : "1"
    emitMetadata : "0"
    inputPosition : "bottom"
    theme : "preferred_color_scheme"
    lang : "en"
    loading : "lazy"

assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"

permalinks:
  categories: "/blog/categories/:slug/"
  tags: "/blog/tags/:slug/"
  #blog: "/blog/:filename" Think through this change
   
module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

